### ISSUE TITLE
Request: Flatpak Version 

### ISSUE THREAD

**Issue by crimsonthunder** [k4yt3x/video2x#1224]
Hello, and thank you for the fantastic work on Video2x! I truly appreciate the time and effort put into making this app.

Would it be possible to create a Flatpak version of Video2x? A Flatpak version would be incredibly helpful, as it allows for easier installation, and compatibility across different Linux distributions. This could make Video2x more accessible to a broader range of linux users and simplify updates as well.

Thank you very much for considering this request and thank you again for your hard work.

**Comment by k4yt3x** [comment]
Interesting suggestion. It may also be easier to recommend flatpak than asking people to use the Docker image. I'll look into it to see how hard it is to make a flatpak package. If it's not too difficult maybe I could release flatpak or AppImage instead of deb files only for Ubuntu.

**Comment by k4yt3x** [comment]
I gave it a try, ran into some issues:

![image](https://github.com/user-attachments/assets/9bccabd8-c150-4aeb-99e1-fe7db2c08f64)

```yaml
app-id: com.github.k4yt3x.video2x
runtime: org.freedesktop.Platform
runtime-version: "23.08"
sdk: org.freedesktop.Sdk
command: video2x
finish-args:
  - --share=network
  - --share=ipc
  - --socket=x11
  - --socket=wayland
  - --device=dri
  - --env=LD_LIBRARY_PATH=/app/lib

modules:
  - name: video2x
    buildsystem: cmake
    builddir: true
    config-opts:
      - -DUSE_SYSTEM_OPENCV=OFF
      - -DUSE_SYSTEM_NCNN=OFF
      - -DUSE_SYSTEM_SPDLOG=OFF
      - -DUSE_SYSTEM_BOOST=OFF
    sources:
      - type: git
        url: https://github.com/k4yt3x/video2x.git
        branch: master
        submodules: true

cleanup:
  - /include
  - /share/man
  - /share/doc
  - /share/gtk-doc
```

I'll just leave this here for now for anyone experienced with Flatpak to try. I'll probably get back to this after implementing frame interpolation.

**Comment by k4yt3x** [comment]
An update to this feature. I've successfully packed it and it's working on my machine. More tests are needed. Next release should cone with a flatpak package.

![image](https://github.com/user-attachments/assets/c190be24-273b-415a-8000-1c2890c2ca41)

**Comment by crimsonthunder** [comment]
Wow! Good News! Thank you for your work 😊

K4YT3X ***@***.***> schrieb am Do., 19. Dez. 2024, 06:38:

**Comment by crimsonthunder** [comment]
> I gave it a try, ran into some issues:
> 
> ![image](https://private-user-images.githubusercontent.com/21986859/384656032-9bccabd8-c150-4aeb-99e1-fe7db2c08f64.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUzNzM0OTIsIm5iZiI6MTczNTM3MzE5MiwicGF0aCI6Ii8yMTk4Njg1OS8zODQ2NTYwMzItOWJjY2FiZDgtYzE1MC00YWViLTk5ZTEtZmU3ZGIyYzA4ZjY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI4VDA4MDYzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE0MDlhOTRmMjJjMGEzODFlMjVjZTI5Mzg0OGQxNzYwMTJlZTNlZDQxODA1NjQzYzBmMjJkNzZkM2YzODY5ODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.vyZHR0p78HTKpU24olSQX-HoYY4QkXIixbgHFMe4WRA)
> 
> ```yaml
> app-id: com.github.k4yt3x.video2x
> runtime: org.freedesktop.Platform
> runtime-version: "23.08"
> sdk: org.freedesktop.Sdk
> command: video2x
> finish-args:
>   - --share=network
>   - --share=ipc
>   - --socket=x11
>   - --socket=wayland
>   - --device=dri
>   - --env=LD_LIBRARY_PATH=/app/lib
> 
> modules:
>   - name: video2x
>     buildsystem: cmake
>     builddir: true
>     config-opts:
>       - -DUSE_SYSTEM_OPENCV=OFF
>       - -DUSE_SYSTEM_NCNN=OFF
>       - -DUSE_SYSTEM_SPDLOG=OFF
>       - -DUSE_SYSTEM_BOOST=OFF
>     sources:
>       - type: git
>         url: https://github.com/k4yt3x/video2x.git
>         branch: master
>         submodules: true
> 
> cleanup:
>   - /include
>   - /share/man
>   - /share/doc
>   - /share/gtk-doc
> ```
> 
> I'll just leave this here for now for anyone experienced with Flatpak to try. I'll probably get back to this after implementing frame interpolation.

Is the yaml still up to date?

**Comment by k4yt3x** [comment]
Here's the latest I have. I have yet figured out the full process of submitting it to the flatpak repo. Also, since the flatpak FFmpeg is built without libplacebo and non-free encoders, support for libplacebo (Anime4K) and a lot of encoders (e.g., nvenc) are missing.

```yaml
app-id: io.github.k4yt3x.Video2X
runtime: org.freedesktop.Platform
runtime-version: "24.08"
sdk: org.freedesktop.Sdk
command: video2x
add-extensions:
  org.freedesktop.Platform.ffmpeg-full:
    version: "24.08"
    directory: lib/ffmpeg
    add-ld-path: .
cleanup-commands:
  - mkdir -p ${FLATPAK_DEST}/lib/ffmpeg
finish-args:
  - --device=all
  - --share=ipc
  - --socket=x11
  - --socket=wayland
  - "--env=LC_ALL=C.UTF-8"
  - "--env=LANG=C.UTF-8"
  - --filesystem=home
modules:
  - name: video2x
    buildsystem: cmake
    builddir: true
    config-opts:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_INSTALL_PREFIX=/app
      - -DBUILD_SHARED_LIBS=OFF
      - -DUSE_SYSTEM_BOOST=OFF
      - -DUSE_SYSTEM_SPDLOG=OFF
      - -DUSE_SYSTEM_NCNN=OFF
      - -DNCNN_AVX512=OFF
      - -DSPDLOG_NO_EXCEPTIONS=ON
    sources:
      - type: git
        url: https://github.com/k4yt3x/video2x.git
        branch: master
```

**Comment by k4yt3x** [comment]
I haven't been able to make much progress on Flatpak due to the Flatpak FFmepg being too old. It currently runs, but lacks a lot of codecs and doesn't have libplacebo. On the other hand, I was able to pack it into a pretty usable AppImage. Although I'm more of a fan of how Flatpak acts more like a package manager and helps manage stuff a little more elegantly, the AppImage does seem to work better atm.

You can already get the latest AppImage in the [pipeline build artifacts](https://github.com/k4yt3x/video2x/actions/runs/12720272147) if you want to give it a try:

![image](https://github.com/user-attachments/assets/56b0d804-6557-47e3-97b5-8c0618704034)

I don't quite want to maintain too many packages at once. If the flatpak version works so poorly, I might just maintain an AppImage instead. If anyone still wants to take a crack at the flatpak version, here's the latest config:

```yaml
app-id: io.github.k4yt3x.Video2X
runtime: org.freedesktop.Platform
runtime-version: "24.08"
sdk: org.freedesktop.Sdk
command: video2x
add-extensions:
  org.freedesktop.Platform.ffmpeg-full:
    version: "24.08"
    directory: lib/ffmpeg
    add-ld-path: .
cleanup-commands:
  - mkdir -p ${FLATPAK_DEST}/lib/ffmpeg
finish-args:
  - --device=all
  - --share=ipc
  - --socket=x11
  - --socket=wayland
  - --env=LC_ALL=C.UTF-8
  - --env=LANG=C.UTF-8
  - --filesystem=home
modules:
  - name: video2x
    buildsystem: cmake
    builddir: true
    config-opts:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_INSTALL_PREFIX=/app
      - -DBUILD_SHARED_LIBS=OFF
      - -DVIDEO2X_USE_EXTERNAL_BOOST=OFF
      - -DVIDEO2X_USE_EXTERNAL_SPDLOG=OFF
      - -DVIDEO2X_USE_EXTERNAL_NCNN=OFF
      - -DNCNN_AVX512=OFF
    sources:
      - type: git
        url: https://github.com/k4yt3x/video2x.git
        branch: master
```
