### ISSUE TITLE
Waifu2x NCNN Vulkan doesn't use custom settings

### ISSUE THREAD

**Issue by SonOfDiablo** [k4yt3x/video2x#435]
## Component Versions

Please at least fill in the release version and GUI or CLI version.

- **Video2X release version**: 4.8.1
- **Upscaler version**: 4.4.1
- **GUI version**: 2.8.1
- **CLI version**: 4.3.1

## Symptom

The "-j" option doesn't seem to be read from the config file when using Waifu2x NCNN Vulkan (I haven't tested other drivers)
I have tried changing it but it always use 1:1:1 

## Error Log or Screenshots

My settings for Waifu2x NCNN Vulkan:
```
waifu2x_ncnn_vulkan:
  path: 'dependencies\waifu2x-ncnn-vulkan\waifu2x-ncnn-vulkan'
  v: null # verbose output
  #i: null # input-path: input image path (jpg/png/webp) or directory
  #o: null # output-path: output image path (jpg/png/webp) or directory
  'n': 2 # noise-level: denoise level (-1/0/1/2/3, default=0)
  s: 2 # scale: upscale ratio (1/2, default=2)
  t: 400 # tile-size: tile size (>=32, default=400)
  m: null # model-path: waifu2x model path (default=models-cunet)
  g: 0 # gpu-id: gpu device to use (default=0)
  j: '1:2:2' # thread count for load/proc/save (default=1:2:2) can be 1:2,2,2:2 for multi-gpu
  x: false # enable tta mode
  #f: png # output image format (jpg/png/webp, default=ext/png)
```

The command used (according to the console output):
```
c:\Program Files\Video2x\dependencies\waifu2x-ncnn-vulkan\waifu2x-ncnn-vulkan -n 2 -s 2 -t 400 -m c:\Program Files\Video2x\dependencies\waifu2x-ncnn-vulkan\models-cunet -g 0 -j 1:1:1 -f png -i C:\Users\USRNAME\AppData\Local\Temp\video2x\tmpxoz8fy8q -o C:\Users\USRNAME\AppData\Local\Temp\video2x\tmpucf9pnaw
```
